#!/bin/bash

obtemHtmlCompleto(){

  curl https://finance.yahoo.com/quote/$1/options?p=$1 > stock.options.$1.html 2> /dev/null

}

quebraLinhasParaFazerFiltro(){
  
  sed -r 's/\s/\n/g' stock.options.$1.html > stock.options.$1.html.formatted

}

filtraValorFechamento(){

  while read line
  do

     if [ "$line" = "in-the-money" ]
     then 
        flagITM=1     
     fi

     if [ "${line:0:13}" = "in-the-money_" ]
     then 
        if [ "$flagITM" = "1" ]
        then
           flagITM=0
        else
           flagOTM=1
        fi
     fi

     if [ "$flagOTM" = "1" ]
     then

         if [ "${line:0:5}" = "href=" ]
         then 
            if [ "$flagNomeJaObtido" != "1" ]
            then
               result=$(echo $line | cut -d'=' -f2 | cut -d'/' -f3 | cut -d'?' -f1)
               flagNomeJaObtido=1
            fi
         fi

         if [ "${line:0:16}" = "class=\"data-col3" ]
         then
            flagObtemLastPrice=1
         fi

         if [[ "$flagObtemLastPrice" == "1" && "${line:0:12}" == "data-reactid" ]]
         then
            result=$(echo $result";"$(echo $line | cut -d'>' -f2 | cut -d'<' -f1))
            echo $result
            exit
         fi

     fi

  done < stock.options.$1.html.formatted

}

if [ -z "$1" ]
then 
   echo "Digitar o simbolo de um ativo como parametro."
   exit 1
fi

obtemHtmlCompleto $1
quebraLinhasParaFazerFiltro $1
echo $(filtraValorFechamento $1)
rm stock.options.$1.*
