#!/usr/bin/bash

obtemHtmlCompleto(){

  curl https://finance.yahoo.com/quote/$1?p=$1 > stocks.$1.html 2> /dev/null

}

quebraLinhasParaFazerFiltro(){
  
  sed -r 's/\s/\n/g' stocks.$1.html > stocks.$1.html.formated

}

filtraValorFechamento(){

  grep 'reactid="29"' stocks.$1.html.formated > stocks.$1.html.formated.filtered
  echo $(cat stocks.$1.html.formated.filtered) | cut -d'<' -f2 | cut -d'>' -f2 

}

if [ -z "$1" ]
then 
   echo "Digitar o simbolo de um ativo como parametro."
   exit 1
fi

obtemHtmlCompleto $1
quebraLinhasParaFazerFiltro $1
echo "$(filtraValorFechamento $1)"
rm stocks.$1.*

