#!/usr/bin/bash

cleanStocksSpecialChars(){

    grep -v "[\^\\\/]" ../files/stock.list.all > cleanStocksSpecialChars.tmp.file
    mv cleanStocksSpecialChars.tmp.file ../files/stock.list.all.clean

}

calcNumberOfTasks(){

    linesPerTasks=500
    totalStocks=$(cat ../files/stock.list.all.clean | wc -l)
    numberOfTasks=$(expr $totalStocks / $linesPerTasks)
    remainder=$(expr $totalStocks % $linesPerTasks)

    if [ "$numberOfTasks" -lt "1" ]
    then
        numberOfTasks=1
    else
        if [ "$remainder" -ne "0" ]
        then
            numberOfTasks=$(expr $numberOfTasks + 1)
        fi
    fi

}

main(){

    count=1
    beginLine=0

    cleanStocksSpecialChars
    calcNumberOfTasks

    while [ "$count" -le "$numberOfTasks" ] 
    do
        ./runSearch $beginLine $linesPerTasks & 2> /dev/null >/dev/null
        count=$(expr $count + 1)
        beginLine=$(expr $beginLine + $linesPerTasks + 1)
    done
    
}

main