#!/usr/bin/bash

cleanStocksSpecialChars(){

    grep -v "[\^\\\/]" ..~/archive/files/stock.list.all > cleanStocksSpecialChars.tmp.file
    mv cleanStocksSpecialChars.tmp.file ..~/archive/files/stock.list.all.clean

}

getParameters(){
    linesPerTask=$(grep "^linesPerTask" ./preprocessing.conf | cut -d'=' -f2)
}

calcNumberOfTasks(){

    totalStocks=$(cat ..~/archive/files/stock.list.all.clean | wc -l)
    numberOfTasks=$(expr $totalStocks / $linesPerTask)
    remainder=$(expr $totalStocks % $linesPerTask)

    if [ "$numberOfTasks" -lt "1" ]
    then
        numberOfTasks=1
    else
        if [ "$remainder" -ne "0" ]
        then
            numberOfTasks=$(expr $numberOfTasks + 1)
        fi
    fi

}

main(){

    count=1
    beginLine=0

    cleanStocksSpecialChars
    getParameters
    calcNumberOfTasks

    echo $(date "+%D %H:%M:%S") " -------------->>>> INICIO <<<<------------------ " >> ..~/archive/logs/preprocessing.log

    while [ "$count" -le "$numberOfTasks" ] 
    do
        ./runSearch $beginLine $linesPerTask & 2> /dev/null > /dev/null
        count=$(expr $count + 1)
        beginLine=$(expr $beginLine + $linesPerTask)
    done
    
    echo $(date "+%D %H:%M:%S") " -------------->>>> FIM <<<<------------------ " >> ..~/archive/logs/preprocessing.log

}

main