#!/usr/bin/bash

stockSymbol=0
stockData=0
stockOptionData=0

runListSearch(){

    echo "$(date "+%D %H:%M:%S") ---- Initializing search for Stocks and Options Price" >> ../logs/extractor.log
    
    while read line
    do
        stockSymbol=$line
        stockData=$(./util/goFishingStocks $line)
        stockOptionsData=$(./util/goFishingStockOptions $line)
        echo $(date +%d/%m)";"$stockSymbol";"$stockData";"$stockOptionsData
        echo "$(date "+%D %H:%M:%S") ---- Consultando: " $line >> ../logs/extractor.log
    done < ../files/presets.stocks.with.options

    echo "$(date "+%D %H:%M:%S") ---- Ending search for Stocks and Options Price" >> ../logs/extractor.log

}

runListSearch > ../files/extractor.prices.papers.and.options
chmod 444 ../files/extractor.prices.papers.and.options