#!/usr/bin/bash

runAddExtraInfo(){
    while read line
        do
        optionAll=$(echo $line | cut -d';' -f5 | sed 's/[A-Z]//g')
        optionExpiryYear=${optionAll:0:2}
        optionExpiryMonth=${optionAll:2:2}
        optionExpiryDay=${optionAll:4:2}
        optionStrike=$(echo ${optionAll:6:5}"."${optionAll:11:2})
        echo $line";"$optionExpiryDay"/"$optionExpiryMonth"/"$optionExpiryYear";"$(echo $optionStrike+0|bc)
    done < ../files/extractor.prices.papers.and.options
}

runAddExtraInfo
